### ISSUE TITLE
unable to write image 

### ISSUE THREAD

**Issue by philippkeller** [MacGapProject/MacGap1#145]
I have put an application.png into /var/tmp/goodbudget, but when building I get this:

```
$ macgap build goodbudget
Error: Unable to write image to file /private/var/tmp/goodbudget/application.icns.L1zan
Built application in /private/var/tmp/goodbudget.app
```

`touch`ing the file works:

```
touch /private/var/tmp/goodbudget/application.icns.L1zan
```

I tried with different PNG images, all without luck

**Comment by philippkeller** [comment]
is macgap still working / under development? Judging from the last commits and the lack of communication in the issues it looks like it has currently no contributors. I have switched to Electron now, the pro for Electron is that it is actively developed and has many features but the pro for MacGap is it's ease of use (and the fact that Slack uses MacGap for their OS X app)

**Comment by jeff-h** [comment]
Hi — MacGap v1 is definitely not still under development. I'm happy to leave it up, as numerous people are still using it and I'm hoping they will help each other in this issue queue where they can.

MacGap v2 is also very quiet. I don't personally use it, having switched to Swift, but the concept is great, and I am very open to code contributions.

I guess we're just growing used to gigantic app sizes, so for many people the larger communities, corporate sponsorship and consequent active development around big fat projects like Electron is understandably attractive.

I think there remains a place for MacGap, as to this day I am not aware of any other lightweight alternative to Electron etc

**Comment by philippkeller** [comment]
thanks for the reply @jeff-h, didn't realize that MacGap is smaller in filesize. Would be great if Slack would contribute back to MacGap as I reckon they have made some changes in the macgap codebase

**Comment by jeff-h** [comment]
The MacGap project is extremely lightweight and nimble; a blank application is about 980KB. The Electron apps I have in my Apps folder range from 135MB (Postman) to 245MB (GitKraken)!
