### ISSUE TITLE
Add global keyboard shortcuts (Hotkeys)

### ISSUE THREAD

**Issue by hay** [MacGapProject/MacGap1#17]
It would be great to have a way to add global window shortcuts, for example to add global play/pause to a music application.

Maybe something like:

macgap.menu.addHotKey("cmd-alt-p", function() {
    window.App.pauseSound();
});

**Comment by blakewilson** [comment]
Has the decision for this feature changed at all since 2012?

**Comment by jeff-h** [comment]
If a PR was offered in https://github.com/MacGapProject/MacGap2 I would roll it in. I think it would add something valuable to the kinds of apps likely built with MacGap.
