### ISSUE TITLE
How to get the URL for newly created (or redirected) page?

### ISSUE THREAD

**Issue by mechiland** [MacGapProject/MacGap1#34]
So like most of the OAuth 2.0 links, like this: 

window.open("target-oauth-2.0-url")

// You authorize it 
// OAuth server will redirect with special sort of "accee token"
// The webview browser will actually redirect to "your-callback-url?#access_code=newly_created"

Then how do we get the url so that we can parse the access_code for later use?

**Comment by eliasisrael** [comment]
@mechiland Did you ever find a way to do this reliably?

**Comment by jeff-h** [comment]
@eliasisrael Just thought I'd check that you definitely mean to be in the MacGap 1 issue queue? MacGap 2 is a complete rewrite and no further development is planned for v1.

**Comment by eliasisrael** [comment]
Good call, @jeff-h ; you're right that I'm trying to get this figured out for MacGap2.
