### ISSUE TITLE
API call to set User-Agent

### ISSUE THREAD

**Issue by wfaulk** [MacGapProject/MacGap1#88]
I am trying to create a macgap application for the VMware vCenter Web Client.  It checks User-Agent and shows a banner if it's not one of the supported clients.  It might also change its feature set based on User-Agent.

It would be nice if macgap provided an API call to set the User-Agent to an arbitrary value.

**Comment by kartikluke** [comment]
Setting custom user agent doesn't seem to be working or I've made a mistake somewhere:
```
<script type="text/javascript" charset="utf-8">
      macgap.app.setCustomUserAgent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36');
      macgap.growl.notify({title: 'MacGap', content: navigator.userAgent});
  </script>
```

Also how do I go about debugging MacGap apps, finding it a bit hard to figure out. @jeff-h

**Comment by jeff-h** [comment]
Just confirming, you're using MacGap 1 for this?

**Comment by kartikluke** [comment]
Hey. I cloned the repo and it worked, the macgap gem is pretty old. I was trying to make a MacGap version of web.whatsapp.com but that didn't end up working.
